spring:
  application:
    name: springcloud-netflix-eureks-feign
server:
  port: 8767

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 3000
        requestVolumeThreshold: 10
        errorThresholdPercentage: 50